language: ruby
rvm:
- 2.7.1
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
notifications:
  slack:
    secure: TOTvJY/5Mtm3lklekgStNNP8dJIMNkY//m6UKEfZPez9C3+8qkgwbaZPqQ3q1yu4vKzk+qP0y1bPOLm5XVGPFmVyvSgbwp3SSn+zWNeUseuwHrZbWeClFnzby+2GaKuZdaEGsSgVZpuz1kPgOEsGxn33ApwvMf4+btb9BnkqNDdlhW0zffGqF/Qy+VtCFHzoVOx9M5/Jm7LXBbIbw5As4lf5w1Ixzi+n2iE0e4Dt1MGzu84oOdUN87dfrMlWO+QWWyLR1NQTVGTCZE1nii4W9wIAOiFVElm2+oBfTYjPw+dmWvzThpvO6JKxxBc1s/kQp1XmTKQSjrBIOvFSVmCUdH9Kj7xAbPnm4Vl3ZTFagNdNlRpVhUbm9NV4GiRgL4O6NpExPz4TQdMYwZdQ46lbP6tNb/SYV6w99PZxn4uqP5QHecLIjAO0zQmn4lVV5NVfdfzIy8uhmflv+nrtu5lY6x9LyfKVt9TlD69gHp1tFJFbSeCge78QTatJxxUJ0+IvvaRv+m9SDDQqFsIzs1+PnSlPgxP2u2n6DdUELNEwZJC2qrYit8kHvqK3298RuaxKFEft2+a+L4KcFcP3dYn/d9PhgPYfldHPKokbYWoUITC+q71KvMlI1YgLmvg4R3+7/mP4WW9Iup3BGNuwG8e4GO2dOhOJUiTRw+Uyh0xcPQM=
