- name: Product 1
  description: This is a Product, neat huh?
- name: Product 2
  description: This is a Product, neat huh?
- name: Product 3
  description: This is a Product, neat huh?
- name: Product 4
  description: This is a Product, neat huh?
- name: Product 5
  description: This is a Product, neat huh?
