- name: Thingy 1
  description: This is a Thingy product, neat huh?
- name: Thingy 2
  description: This is a Thingy product, neat huh?
- name: Thingy 3
  description: This is a Thingy product, neat huh?
- name: Thingy 4
  description: This is a Thingy product, neat huh?
- name: Thingy 5
  description: This is a Thingy product, neat huh?
