- name: Carved in single tea light holder
  url: https://www.etsy.com/uk/listing/602486470/carved-in-single-tea-light-holder
  img: /img/product1.jpg
- name: Branch tealight holder
  url: https://www.etsy.com/uk/listing/601788128/branch-tealight-holder
  img: /img/product2.jpg
- name: Slanted beech tea light holder
  url: https://www.etsy.com/uk/listing/601786078/slanted-beech-tea-light-holder
  img: /img/product3.jpg
- name: Beautiful beech candle holder
  url: https://www.etsy.com/uk/listing/601783694/beautiful-beech-candle-holder
  img: /img/product4.jpg
- name: Wooden single tealight holder
  url: https://www.etsy.com/uk/listing/601781774/wooden-single-tealight-holder
  img: /img/product5.jpg
- name: Wooden handmade double tealight holder
  url: https://www.etsy.com/uk/listing/601773618/wooden-handmade-double-tealight-holder
  img: /img/product6.jpg
- name: Button Sweetheart Wooden Heart
  url: https://www.etsy.com/uk/listing/578592510/button-sweetheart-wooden-heart
  img: /img/product7.jpg
