- name: Product 1
  description: This is a Product, neat huh?
- name: Product 2
  description: This is a Product, neat huh?
- name: Product 3
  description: This is a Product, neat huh?
- name: Product 4
  description: This is a Product, neat huh?
- name: Product 5
  description: This is a Product, neat huh?
- name: Product 6
  description: This is a Product, neat huh?
- name: Product 7
  description: This is a Product, neat huh?
- name: Product 8
  description: This is a Product, neat huh?
- name: Product 9
  description: This is a Product, neat huh?
