- name: Product 1
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 2
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 3
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 4
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 5
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 6
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 7
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 8
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
- name: Product 9
  description: This is a Product, neat huh?
  url: /products/product
  image: /img/product.jpg
