- name: Service 1
  description: This is a Service, neat huh?
- name: Service 2
  description: This is a Service, neat huh?
- name: Service 3
  description: This is a Service, neat huh?
- name: Service 4
  description: This is a Service, neat huh?
- name: Service 5
  description: This is a Service, neat huh?
