- name: Service 1
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 2
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 3
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 4
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 5
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 6
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 7
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 8
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
- name: Service 9
  description: This is a Service, neat huh?
  url: /services/service
  img: /img/service.jpg
  price: 50.00
